# Generated by Django 5.1.7 on 2025-06-09 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_test_testresult_questionresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(help_text='The code/password students must reveal or guess', max_length=50)),
                ('order', models.IntegerField(help_text='Order within the sequence (0-based)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='quest.test')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='quest.questsequence')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('sequence', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed_letters', models.JSONField(default=list, help_text='List of revealed letter positions')),
                ('is_completed', models.BooleanField(default=False)),
                ('code_guessed', models.BooleanField(default=False)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_answers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='quest.quest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'quest')},
            },
        ),
        migrations.CreateModel(
            name='SequenceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_quests', models.JSONField(default=list, help_text='List of completed quest IDs')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quest.quest')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='quest.questsequence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'sequence')},
            },
        ),
    ]
